-- Ejecutar UNA sola vez en Supabase > SQL Editor.
-- Crea la tabla que guarda las marcas destacadas que verán los trabajadores.
create table if not exists public.marcas_destacadas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text,
  imagen_url text,
  orden integer not null default 1,
  activo boolean not null default true,
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

-- Para este proyecto web, las políticas permiten al frontend usar la tabla con la publishable key,
-- igual que las tablas actuales del sistema. En producción se recomienda migrar a Supabase Auth + RLS por rol.
alter table public.marcas_destacadas enable row level security;

drop policy if exists "marcas_destacadas_select" on public.marcas_destacadas;
drop policy if exists "marcas_destacadas_insert" on public.marcas_destacadas;
drop policy if exists "marcas_destacadas_update" on public.marcas_destacadas;
drop policy if exists "marcas_destacadas_delete" on public.marcas_destacadas;

create policy "marcas_destacadas_select" on public.marcas_destacadas for select using (true);
create policy "marcas_destacadas_insert" on public.marcas_destacadas for insert with check (true);
create policy "marcas_destacadas_update" on public.marcas_destacadas for update using (true) with check (true);
create policy "marcas_destacadas_delete" on public.marcas_destacadas for delete using (true);

insert into public.marcas_destacadas (nombre,categoria,imagen_url,orden,activo)
select * from (values
  ('Marsella','Detergentes',null,1,true),
  ('Opal','Detergentes',null,2,true),
  ('Bolívar','Detergentes',null,3,true),
  ('Ace','Detergentes',null,4,true),
  ('Ariel','Detergentes',null,5,true),
  ('Doff','Detergentes',null,6,true),
  ('Patito','Detergentes',null,7,true)
) as v(nombre,categoria,imagen_url,orden,activo)
where not exists (select 1 from public.marcas_destacadas);
